> # Numpy

In [1]:
import numpy as np #hello
np.__version__

'1.21.5'

In [2]:
#Create 2 arrrays and add them
 
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [3]:
# Add a scalar to every number in array

a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [5]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [10]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [11]:
#identity matraix

i = np.eye(4)

print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# RESHAPE 
c = np.array([x for x in range(27)])
c.shape

(27,)

In [14]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
c.reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
d = np.array([[2.5, 3.8, 1.5], [4.7,2.9,1.56]])
d.astype('int')

array([[2, 3, 1],
       [4, 2, 1]])

In [17]:
e = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

a.astype('bool')

array([[ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#stacking
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
np.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
list = [x for x in range(0,101,2)]
np.array(list)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [21]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4], dtype=int64),)


In [22]:
# equally spaced numbers within a specified range

np.linspace(0,3,20)

array([0.        , 0.15789474, 0.31578947, 0.47368421, 0.63157895,
       0.78947368, 0.94736842, 1.10526316, 1.26315789, 1.42105263,
       1.57894737, 1.73684211, 1.89473684, 2.05263158, 2.21052632,
       2.36842105, 2.52631579, 2.68421053, 2.84210526, 3.        ])

In [27]:
a = np.array([[1,2,3],
              [4,5,6]])

o = np.hstack((a,a,a,a,a))

print(o)

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [28]:
#random array gen
np.random.seed(123) # setting the seed

o = np.random.randint(0, 10, size = (5,5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [29]:
np.random.seed(123) # setting the seed

o = np.random.normal(size = (3,3))

print(o)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]]


In [30]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = a@b

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [31]:
np.dot(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [32]:
len(a)

3

In [34]:
a.shape

(3, 3)

In [35]:
a.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U11')

In [36]:
type(a)

numpy.ndarray

In [41]:
e = np.random.randint(0, 20, size = (5,5))
e

array([[18, 17,  1, 19, 12],
       [ 9, 16, 17,  3,  3],
       [11,  7,  9,  2,  3],
       [11,  3, 19,  6,  9],
       [14,  6, 19,  6, 12]])

In [42]:
e.sort()
print(e)

[[ 1 12 17 18 19]
 [ 3  3  9 16 17]
 [ 2  3  7  9 11]
 [ 3  6  9 11 19]
 [ 6  6 12 14 19]]


In [45]:
e.sort(axis=0)
print(e)

[[ 1  3  7  9 11]
 [ 2  3  9 11 17]
 [ 3  6  9 14 19]
 [ 3  6 12 16 19]
 [ 6 12 17 18 19]]


In [46]:
e.sort(axis=1)
print(e)

[[ 1  3  7  9 11]
 [ 2  3  9 11 17]
 [ 3  6  9 14 19]
 [ 3  6 12 16 19]
 [ 6 12 17 18 19]]


In [47]:
f = e.copy()
f

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [48]:
f + 2

array([[ 3,  5,  9, 11, 13],
       [ 4,  5, 11, 13, 19],
       [ 5,  8, 11, 16, 21],
       [ 5,  8, 14, 18, 21],
       [ 8, 14, 19, 20, 21]])

In [49]:
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [50]:
f = np.array([2,3])
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [51]:
g = np.copy(e)
g

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [52]:
g = np.array([2,5])
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [55]:
np.append(e,f)

array([ 1,  3,  7,  9, 11,  2,  3,  9, 11, 17,  3,  6,  9, 14, 19,  3,  6,
       12, 16, 19,  6, 12, 17, 18, 19,  2,  3])

In [57]:
np.append(e, np.array([[2,3,4], [2,8,9]]))

array([ 1,  3,  7,  9, 11,  2,  3,  9, 11, 17,  3,  6,  9, 14, 19,  3,  6,
       12, 16, 19,  6, 12, 17, 18, 19,  2,  3,  4,  2,  8,  9])

In [58]:
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [60]:
np.insert(e, 1,2, 0) # second row is inserted with all values as 2

array([[ 1,  3,  7,  9, 11],
       [ 2,  2,  2,  2,  2],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [61]:
np.insert(e, 1,2, 1) # second col is inserted with all values as 2

array([[ 1,  2,  3,  7,  9, 11],
       [ 2,  2,  3,  9, 11, 17],
       [ 3,  2,  6,  9, 14, 19],
       [ 3,  2,  6, 12, 16, 19],
       [ 6,  2, 12, 17, 18, 19]])

In [67]:
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [69]:
np.delete(e, 1,0) # delete 1st row of e.

array([[ 1,  3,  7,  9, 11],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [71]:
np.delete(e, 0, 1) # delete 0st column of e.

array([[ 3,  7,  9, 11],
       [ 3,  9, 11, 17],
       [ 6,  9, 14, 19],
       [ 6, 12, 16, 19],
       [12, 17, 18, 19]])

In [73]:
e.flatten()

array([ 1,  3,  7,  9, 11,  2,  3,  9, 11, 17,  3,  6,  9, 14, 19,  3,  6,
       12, 16, 19,  6, 12, 17, 18, 19])

In [74]:
np.linalg.inv(e)  # inverse of matrix e.

array([[-1.73863636,  0.26136364, -0.23863636,  1.04545455, -0.03409091],
       [ 0.79734848, -0.20265152,  0.38068182, -0.81060606,  0.14962121],
       [ 0.21590909,  0.21590909, -0.28409091, -0.13636364,  0.10227273],
       [-0.32386364, -0.32386364, -0.07386364,  0.70454545, -0.15340909],
       [ 0.15909091,  0.15909091,  0.15909091, -0.36363636,  0.02272727]])

In [75]:
np.sqrt(e)

array([[1.        , 1.73205081, 2.64575131, 3.        , 3.31662479],
       [1.41421356, 1.73205081, 3.        , 3.31662479, 4.12310563],
       [1.73205081, 2.44948974, 3.        , 3.74165739, 4.35889894],
       [1.73205081, 2.44948974, 3.46410162, 4.        , 4.35889894],
       [2.44948974, 3.46410162, 4.12310563, 4.24264069, 4.35889894]])

In [76]:
np.array_equal(e, np.sqrt(e))

False

In [78]:
np.mean(e)

10.08

In [79]:
np.median(e)

9.0

In [81]:
np.std(e)

5.89182484464703

In [82]:
np.sum(e)

252

In [85]:
np.min(e)

1

In [86]:
np.max(e)

19

In [88]:
e

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [87]:
e[1] # gives the 2nd row

array([ 2,  3,  9, 11, 17])

In [89]:
e[2:5] #from 2nd to 4th row

array([[ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [91]:
e[2:5, 2:5]

array([[ 9, 14, 19],
       [12, 16, 19],
       [17, 18, 19]])

In [92]:
e[2<4]

array([[[ 1,  3,  7,  9, 11],
        [ 2,  3,  9, 11, 17],
        [ 3,  6,  9, 14, 19],
        [ 3,  6, 12, 16, 19],
        [ 6, 12, 17, 18, 19]]])

In [96]:
e[-1]

array([ 6, 12, 17, 18, 19])

In [97]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [98]:
np.zeros((3,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [100]:
f=e.flatten()
f

array([ 1,  3,  7,  9, 11,  2,  3,  9, 11, 17,  3,  6,  9, 14, 19,  3,  6,
       12, 16, 19,  6, 12, 17, 18, 19])

In [103]:
f[f % 2 == 0]

array([ 2,  6, 14,  6, 12, 16,  6, 12, 18])

In [105]:
# replace all odd numbers with -1
f[f % 2 == 1] = -1
f

array([-1, -1, -1, -1, -1,  2, -1, -1, -1, -1, -1,  6, -1, 14, -1, -1,  6,
       12, 16, -1,  6, 12, -1, 18, -1])

In [106]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
#> [0 1 2 3 4 5 6 7 8 9]
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [108]:
a = np.arange(10)
a.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
e



array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19]])

In [115]:
g=e+3
g

array([[ 4,  6, 10, 12, 14],
       [ 5,  6, 12, 14, 20],
       [ 6,  9, 12, 17, 22],
       [ 6,  9, 15, 19, 22],
       [ 9, 15, 20, 21, 22]])

In [118]:
np.vstack([e,g])

array([[ 1,  3,  7,  9, 11],
       [ 2,  3,  9, 11, 17],
       [ 3,  6,  9, 14, 19],
       [ 3,  6, 12, 16, 19],
       [ 6, 12, 17, 18, 19],
       [ 4,  6, 10, 12, 14],
       [ 5,  6, 12, 14, 20],
       [ 6,  9, 12, 17, 22],
       [ 6,  9, 15, 19, 22],
       [ 9, 15, 20, 21, 22]])

In [123]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b)) # gives the locatiom
np.intersect1d(a,b)

(array([1, 3, 5, 7], dtype=int64),)


array([2, 4])

In [124]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [127]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[5<a]

array([ 6,  9, 10, 27])

In [128]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [129]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [131]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
np.set_printoptions(threshold=20)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Normalize data

In [139]:
amax, amin = a.max(), a.min()
nor = (a - amin)/(amax - amin)
nor

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [140]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [145]:
np.isnan(a).sum()

0

In [146]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [148]:
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

# END